#!/usr/bin/env python3
"""Export the frozen raw-flow cohort to prepared-feature firmware headers.

The C-reference predictions are generated by the saved deployment kernels.
They are checksums for firmware replay, NOT independent accuracy/equivalence
proofs. Original model and golden-vector headers are never modified here.
"""
from __future__ import annotations
import argparse
import hashlib
import json
import shutil
import subprocess
import tempfile
from pathlib import Path
import numpy as np

ROOT = Path(__file__).resolve().parents[1]
MODELS = ["coeff", "lut14", "mlcoeff", "mlp", "dt5"]
HEADERS = ["kan14_coeff_infer.h", "kan14_coeff_int8.h", "q15_mul.h",
           "kan14_lut_infer.h", "kan14_lut_int16.h",
           "kan14_ml_coeff_infer.h", "kan14_ml_coeff_int8.h",
           "mlp16_infer.h", "mlp16_int8.h", "dt5_model.h"]

def sha(path):
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()

def validate(data):
    n = len(data["row_ids"])
    if n != 500 or len(np.unique(data["row_ids"])) != n:
        raise ValueError("The latency cohort must have exactly 500 unique raw row IDs")
    for key, shape, lo, hi in [
        ("row_ids", (n,), 0, 2**32-1), ("y_true", (n,), 0, 1),
        ("kan_Xq", (n,10), -4096, 4096), ("kan_CAT", (n,4), 0, 255),
        ("baseline_Xq", (n,10), -4096, 4096), ("baseline_CAT", (n,4), 0, 255),
        ("dt_Xq", (n,14), -32768, 32767)]:
        a = data[key]
        if a.shape != shape or not np.issubdtype(a.dtype, np.integer):
            raise ValueError(f"{key}: expected integer {shape}, got {a.dtype} {a.shape}")
        if np.any(a < lo) or np.any(a > hi):
            raise ValueError(f"{key}: outside [{lo}, {hi}]")
    if not np.array_equal(data["y_true"], np.tile([1,0], 250)):
        raise ValueError("Expected interleaved attack/normal rows: 1,0,...,1,0")
    # Category offsets in the saved kernels have no bounds checks.
    for key in ("kan_CAT", "baseline_CAT"):
        if np.any(data[key] >= np.array([4,10,14,4])):
            raise ValueError(f"{key}: exceeds saved categorical cardinalities")

def validate_provenance(cohort, metadata_path, source_csv, data):
    """Bind exported inputs to the recorded source and frozen cohort manifest."""
    meta = json.loads(metadata_path.read_text())
    if sha(cohort) != meta["npz_sha256"]:
        raise ValueError("Cohort NPZ differs from its companion manifest; refusing new reference values")
    row_sha = hashlib.sha256(np.asarray(data["row_ids"], dtype="<i8").tobytes()).hexdigest()
    if row_sha != meta["row_ids_sha256"]:
        raise ValueError("Ordered raw row IDs differ from the cohort manifest")
    if meta["n_unique_flows"] != 500 or np.any(data["row_ids"] >= meta["source_rows"]):
        raise ValueError("Cohort size or raw row range differs from source metadata")
    if sha(source_csv) != meta["source_csv_sha256"]:
        raise ValueError("Source CSV differs from the source bound to this cohort")
    if sha(metadata_path.parent / "hardware_raw_flows.csv") != meta["raw_flows_sha256"]:
        raise ValueError("Raw-flow fixture differs from the cohort manifest")
    for name, expected in meta["preprocessing_hashes"].items():
        if sha(metadata_path.parent / name) != expected:
            raise ValueError(f"Preprocessing artifact differs from cohort manifest: {name}")
    return meta

def c_array(name, a, ctype):
    shape = "".join(f"[{n}]" for n in a.shape)
    if a.ndim == 1:
        body = ",\n  ".join(", ".join(str(int(v)) for v in a[i:i+16]) for i in range(0,len(a),16))
    else:
        body = ",\n  ".join("{"+", ".join(str(int(v)) for v in row)+"}" for row in a)
    return f"static const {ctype} {name}{shape} PROGMEM = {{\n  {body}\n}};\n"

def reference(data, compiler):
    source = r'''#include <cstdio>
#include "kan14_coeff_infer.h"
#include "kan14_lut_infer.h"
#include "kan14_ml_coeff_infer.h"
#include "mlp16_infer.h"
#include "dt5_model.h"
int main() {
  int values[42];
  while (scanf("%d", &values[0]) == 1) {
    for(int j=1;j<42;j++) if(scanf("%d", &values[j]) != 1) return 2;
    int16_t kx[10], bx[10], dx[14]; uint8_t kc[4],bc[4];
    for(int j=0;j<10;j++){kx[j]=values[j];bx[j]=values[14+j];}
    for(int j=0;j<4;j++){kc[j]=values[10+j];bc[j]=values[24+j];}
    for(int j=0;j<14;j++)dx[j]=values[28+j];
    printf("%u %u %u %u %u\n", kan14_coeff_predict(kx,kc),
      kan14_lut_predict(kx,kc),kan14_ml_predict(kx,kc),mlp16_predict(bx,bc),dt5_predict(dx));
  }
}
'''
    matrix = np.concatenate([data[k] for k in ("kan_Xq","kan_CAT","baseline_Xq","baseline_CAT","dt_Xq")], axis=1)
    stdin = "\n".join(" ".join(map(str,row)) for row in matrix.astype(np.int32))+"\n"
    with tempfile.TemporaryDirectory(prefix="kan_hw_ref_") as tmp:
        path=Path(tmp); (path/"reference.cpp").write_text(source)
        cmd=[compiler,"-std=c++11","-O2","-I",str(ROOT/"mcu_pio/include"),str(path/"reference.cpp"),"-o",str(path/"reference")]
        subprocess.run(cmd, check=True, capture_output=True, text=True)
        result=subprocess.run([str(path/"reference")], input=stdin, check=True, capture_output=True, text=True)
    lines=[[int(x) for x in line.split()] for line in result.stdout.splitlines()]
    pred=np.asarray(lines,dtype=np.uint8)
    if pred.shape != (500,5) or not np.isin(pred,[0,1]).all():
        raise RuntimeError(f"Invalid C reference output {pred.shape}")
    return pred, source

def main():
    p=argparse.ArgumentParser(description=__doc__)
    p.add_argument("--cohort",type=Path,default=ROOT/"artifacts/finalization/hardware_cohort.npz")
    p.add_argument("--cohort-metadata",type=Path,default=ROOT/"artifacts/finalization/hardware_cohort.json")
    p.add_argument("--source-csv",type=Path,required=True,help="Original CSV; SHA256 must match cohort provenance")
    p.add_argument("--out",type=Path,default=ROOT/"mcu_pio/include/hardware_cohort")
    p.add_argument("--report",type=Path,default=ROOT/"artifacts/finalization/hardware_cohort_export.json")
    p.add_argument("--compiler",default=shutil.which("g++") or shutil.which("c++"))
    args=p.parse_args()
    if not args.compiler: p.error("A host C++ compiler is needed for the saved C reference")
    with np.load(args.cohort,allow_pickle=False) as loaded:
        data={k:loaded[k] for k in loaded.files}
    validate(data)
    meta=validate_provenance(args.cohort,args.cohort_metadata,args.source_csv,data)
    pred, source=reference(data,args.compiler)
    common = """// Generated by scripts/export_hardware_cohort.py; do not edit.
// Same 500 raw flows; prepared-feature timing boundary (preprocessing excluded).
// Expected predictions are COMPILED-C REFERENCES, not independent golden truth.
#pragma once
#include <stdint.h>
#ifdef __AVR__
#include <avr/pgmspace.h>
#else
#ifndef PROGMEM
#define PROGMEM
#endif
#endif
#define HC_N 500
""" + f'#define HC_COHORT_SHA256 "{sha(args.cohort)}"\n'
    common += c_array("HC_ROW_ID",data["row_ids"],"uint32_t")+c_array("HC_Y_TRUE",data["y_true"],"uint8_t")
    prologue='// Generated; compiled-C reference, not independent golden truth.\n#pragma once\n#include "common.h"\n'
    outputs={"common.h":common,
        "kan.h":prologue+c_array("HC_KAN_X",data["kan_Xq"],"int16_t")+c_array("HC_KAN_CAT",data["kan_CAT"],"uint8_t")+c_array("HC_COEFF_EXPECTED",pred[:,0],"uint8_t")+c_array("HC_LUT14_EXPECTED",pred[:,1],"uint8_t"),
        "kan_ml.h":prologue+'#include "kan.h"\n'+c_array("HC_MLCOEFF_EXPECTED",pred[:,2],"uint8_t"),
        "mlp.h":prologue+c_array("HC_MLP_X",data["baseline_Xq"],"int16_t")+c_array("HC_MLP_CAT",data["baseline_CAT"],"uint8_t")+c_array("HC_MLP_EXPECTED",pred[:,3],"uint8_t"),
        "dt.h":prologue+c_array("HC_DT_X",data["dt_Xq"],"int16_t")+c_array("HC_DT5_EXPECTED",pred[:,4],"uint8_t")}
    args.out.mkdir(parents=True,exist_ok=True)
    for name,body in outputs.items(): (args.out/name).write_text(body,encoding="utf-8",newline="\n")
    args.report.parent.mkdir(parents=True,exist_ok=True)
    report={"schema_version":1,"cohort_sha256":sha(args.cohort),
        "cohort_manifest_sha256":sha(args.cohort_metadata),"source_csv_sha256":meta["source_csv_sha256"],
        "row_ids_sha256":meta["row_ids_sha256"],"provenance_checks":"NPZ, ordered IDs, actual source CSV, raw-flow fixture, and preprocessing artifacts match companion manifest","rows":500,"class_counts":{"attack":250,"normal":250},"order":"attack,normal interleaved; unchanged raw row order",
        "measurement_boundary":"prepared features in RAM -> binary decision; input loading, feature engineering and output excluded",
        "energy_subset":"first 20 rows: 10 attack + 10 normal; repeated in fixed order",
        "expected_prediction_provenance":"saved deployment kernels compiled on host; same-kernel replay reference, NOT an independent mathematical or accuracy validation",
        "hardware_measurements_performed":False,
        "compiler":subprocess.run([args.compiler,"--version"],capture_output=True,text=True,check=True).stdout.splitlines()[0],
        "reference_source_sha256":hashlib.sha256(source.encode()).hexdigest(),
        "kernel_header_sha256":{h:sha(ROOT/"mcu_pio/include"/h) for h in HEADERS},
        "generated_header_sha256":{name:sha(args.out/name) for name in outputs},
        "models":{name:{"expected_attack_decisions":int(pred[:,j].sum()),"energy20_expected_attack_decisions":int(pred[:20,j].sum()),"cohort_errors_descriptive_only":int((pred[:,j]!=data["y_true"]).sum())} for j,name in enumerate(MODELS)},
        "coeff_vs_lut14_cohort_disagreements_descriptive_only":int((pred[:,0]!=pred[:,1]).sum())}
    args.report.write_text(json.dumps(report,indent=2)+"\n")
    print(json.dumps({"generated_headers":len(outputs),"rows":500,"report":str(args.report),"hardware_measurements_performed":False}))
if __name__ == "__main__": main()
